### ISSUE TITLE
2 issues using Shellphish

### ISSUE THREAD

**Issue by CortesWasTaken** [zardus/pwnsh#1]
1) Shellphish does not provide a full link. The only link that appears is the shortened one. Very frustrating

2) I'm having issue #1 because I changed some stuff. But before that, it did provide a full Ngrok link. Unfortunately the problem with that link was that it did not work properly and gave me the following error:

![Snapchat sp](https://user-images.githubusercontent.com/72491720/95565278-376c2e80-0a20-11eb-841c-89140347531a.png)

If someone could write down the entire coding I have to do to fix both problems it would mean the world to me. Thanks in advance <3

**Comment by zardus** [comment]
wrong project
